# Generated by Django 2.2.6 on 2019-12-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_analysis',
            name='analyst',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Laboratory.Laboratorist'),
            preserve_default=False,
        ),
    ]
