# Generated by Django 2.2.6 on 2019-12-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0008_auto_20191219_1155'),
        ('nurse', '0002_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nurse.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='record',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Receptionist.Donation_Record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.Nurse'),
        ),
    ]
