# Generated by Django 2.2.6 on 2019-12-23 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_auto_20191219_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
