# Generated by Django 2.2.6 on 2019-12-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0004_auto_20191223_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='record',
        ),
    ]
