# Generated by Django 2.2.6 on 2019-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0004_auto_20191207_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('Fit', 'Fit'), ('UnFit', 'Unfit'), ('Pending', 'Pending')], default='Pending', max_length=13),
        ),
    ]
