# Generated by Django 2.2.6 on 2019-12-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0005_auto_20191218_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('Fit', 'Fit'), ('Pending', 'Pending'), ('UnFit', 'Unfit')], default='Pending', max_length=13),
        ),
    ]
