# Generated by Django 2.2.6 on 2019-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0007_auto_20191218_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('UnFit', 'Unfit'), ('Pending', 'Pending'), ('Fit', 'Fit')], default='Pending', max_length=13),
        ),
    ]
