# Generated by Django 2.2.6 on 2019-12-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0008_auto_20191219_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('Fit', 'Fit'), ('UnFit', 'Unfit'), ('Pending', 'Pending'), ('withdrawn', 'withdrawn')], default='Pending', max_length=13),
        ),
    ]
