# Generated by Django 2.2.6 on 2019-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0009_auto_20191221_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_record',
            name='barcode',
            field=models.ImageField(null=True, upload_to='static/images/donation_record'),
        ),
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('Fit', 'Fit'), ('Pending', 'Pending'), ('withdrawn', 'withdrawn'), ('UnFit', 'Unfit')], default='Pending', max_length=13),
        ),
    ]
