# Generated by Django 2.2.6 on 2019-12-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0010_auto_20191221_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('withdrawn', 'withdrawn'), ('Fit', 'Fit'), ('UnFit', 'Unfit')], default='Pending', max_length=13),
        ),
    ]
