# Generated by Django 2.2.6 on 2019-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0011_auto_20191223_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('UnFit', 'Unfit'), ('withdrawn', 'withdrawn'), ('Fit', 'Fit')], default='Pending', max_length=13),
        ),
    ]
